language: python
sudo: false
cache: pip

python:
  - 3.3
  - 3.4
  - 3.5
  - 3.5-dev
  - 3.6
  - 3.6-dev
  - pypy3.3-5.2-alpha1

env:
  - PYTHONHASHSEED=random

matrix:
  include:
    - python: 2.7
      script:
        - mkdir man1
        - make extensions docs
        - BRZ_PLUGIN_PATH=-site:-user python ./brz selftest --parallel=fork -q

script:
  - mkdir man1
  - make extensions docs
  - BRZ_PLUGIN_PATH=-site:-user python ./brz selftest --parallel=fork -q --load-list python3.passing

install:
  - sudo apt install python-all-dev python3-all-dev
  - travis_retry pip install -U setuptools
  - travis_retry pip install -U pip coverage codecov flake8 testtools paramiko fastimport configobj cython testscenarios six docutils $TEST_REQUIRE

after_success:
  - python -m coverage combine
  - codecov
