language: python
sudo: false
cache: pip

python:
  - 3.3
  - 3.4
  - 3.5
  - 3.5-dev
  - 3.6
  - 3.6-dev
  - pypy3.3-5.2-alpha1

env:
  - PYTHONHASHSEED=random

matrix:
  include:
    - python: 2.7
      script:
        - make check-ci | tee selftest.log | subunit-filter | subunit2pyunit
        - echo `date` ": selftest ends" 1>&2
        - if [ ! -s selftest.log ] ; then exit 1 ; fi
        - subunit-stats < selftest.log

install:
  - sudo apt install python-all-dev python3-all-dev subunit
  - travis_retry pip install -U setuptools
  - travis_retry pip install -U pip coverage codecov flake8 testtools paramiko fastimport configobj cython testscenarios six python-subunit docutils $TEST_REQUIRE

script:
  - mkdir man1
  - make check-ci | tee selftest.log | subunit-filter | subunit2pyunit
  - if [ ! -s selftest.log ] ; then exit 1 ; fi
  - subunit-stats < selftest.log

after_success:
  - python -m coverage combine
  - codecov
